name: Laravel

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1", "8.2"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.python-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        working-directory: ./app

      - name: Install Dependencies
        run: composer install --dev
        working-directory: ./app

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./app

      - name: Make storage directories
        run: |
          mkdir -p storage/app/public
          mkdir -p storage/framework/cache/data/
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/testing
          mkdir -p storage/framework/views
        working-directory: ./app

      - name: Link storage
        run: php artisan storage:link
        working-directory: ./app

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./app

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
        working-directory: ./app

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
        working-directory: ./app

      - name: Lint with phpstan and php-cs-fixer
        run: make lint
